CREATE DATABASE ProzorroData;
GO;
-- Initialization SQL executed by Postgres on first startup
-- Use IF NOT EXISTS so re-running the script is safe

CREATE TABLE public."procuring_entity"
(
    "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "procuring_entity_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "uq_procuring_entity_name" UNIQUE ("name")
);

CREATE TABLE public."business_organisation"
(
    "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "business_organisation_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "uq_business_organisation_name" UNIQUE ("name")
);

CREATE TABLE public."tender"
(
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "external_id" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    "date_created" timestamptz,
    "date_modified" timestamptz,
    "cpv_code" character varying(20) COLLATE pg_catalog."default",
    "status" character varying(50) COLLATE pg_catalog."default",
    "procuring_entity_id" integer,
    "starting_amount" numeric(19,4),
    "contract_total" numeric(19,4),
    "savings" numeric(19,4),
    -- SHA256 hex digest of the tender payload used to detect unchanged records
    "data_hash" character varying(64),

    CONSTRAINT "tender_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "uq_tender_external_id" UNIQUE ("external_id"),
    CONSTRAINT "fk_tender_procuring_entity"
        FOREIGN KEY ("procuring_entity_id")
        REFERENCES public."procuring_entity" ("id")
);

CREATE TABLE public."tender_business_organisation"
(
    "tender_id" bigint NOT NULL,
    "business_organisation_id" integer NOT NULL,

    CONSTRAINT "tender_business_organisation_pkey"
        PRIMARY KEY ("tender_id", "business_organisation_id"),

    CONSTRAINT "fk_tbo_tender"
        FOREIGN KEY ("tender_id")
        REFERENCES public."tender" ("id"),

    CONSTRAINT "fk_tbo_business_organisation"
        FOREIGN KEY ("business_organisation_id")
        REFERENCES public."business_organisation" ("id")
);

CREATE INDEX "ix_tender_procuring_entity_savings"
    ON public."tender" USING btree
    ("procuring_entity_id" ASC NULLS LAST,
     "savings" DESC NULLS FIRST);
CREATE INDEX "ix_tbo_business_organisation"
    ON public."tender_business_organisation" USING btree
    ("business_organisation_id" ASC NULLS LAST,
     "tender_id" ASC NULLS LAST);