<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1a7c32cd-5d1b-44ab-a391-48a4345c9574</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.24.2-preview.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProzorroDataMining.Application\ProzorroDataMining.Application.csproj" />
    <ProjectReference Include="..\ProzorroDataMining.Core\ProzorroDataMining.Core.csproj" />
    <ProjectReference Include="..\ProzorroDataMining.Infrastructure\ProzorroDataMining.Infrastructure.csproj" />
  </ItemGroup>

</Project>
